org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

group=dev.latvian.mods
modId=kubejs
modName=KubeJS
modVersion=8.1.0
minecraftVersion=26.3

curseforge_id=238086
modrinth_id=umyGl7zF

minecraft_version=26.3
supported_versions=26.3

neoforgeVersion=26.3.0.37-beta
neoforgeVersions=[26.3.0.37-beta,)
rhinoVersion=2101.2.8-build.91
tinyServerVersion=1.0.0-build.45
gifLibVersion=1.7
batVersion=2601.1.0-build.8

archVersion=19.0.1
# 26.2: AlmostGradle needed this
reiVersion=26.2.820